package server

import (
	"context"
	"log"
	"net"

	"github.com/google/uuid"
	"github.com/packt-go-course/todo-grpc/proto"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

const (
	PORT = ":50051"
)

type TodoServer struct {
	//to prevent crashes when rpcs are not implemented in server.go,then it uses default versions
	proto.UnimplementedTodoServiceServer
	todos map[string]*proto.Todo
}

// to implement an interface in Go,you must define methods on struct
func (s *TodoServer) CreateTodo(ctx context.Context, in *proto.NewTodo) (*proto.Todo, error) {
	log.Printf("Received: %v", in.GetName())
	todo := &proto.Todo{
		Name:        in.GetName(), //In todo.pb.go , protoc generates also the getter methods
		Description: in.GetDescription(),
		Done:        false,
		Id:          uuid.New().String(), //unique ids generated by go
	}
	return todo, nil
}

func (s *TodoServer) DeleteTod(ctx context.Context, in *proto.TodoId) (*proto.Empty, error) {
	log.Printf("Deleting todo with ID : %s", in.GetId())
	if _, exists := s.todos[in.GetId()]; !exists {
		return nil, status.Error(codes.NotFound, "Todo not found")

	}
	delete(s.todos, in.GetId())
	return &proto.Empty{}, nil //returning empty message
}

func (s *TodoServer) ModifyTodo(ctx context.Context, in *proto.Todo) (*proto.Todo, error) {
	log.Printf("Modifying todo with ID : %s", in.GetId())
	existingTodo, exists := s.todos[in.GetId()]
	if !exists {
		return nil, status.Error(codes.NotFound, "Todo was not found")
	}
	if in.GetName() != "" {
		existingTodo.Name = in.GetName()

	}
	if in.GetDescription() != "" {
		existingTodo.Name = in.GetDescription()

	}
	existingTodo.Done = in.GetDone() //have they finished the task or not
	return existingTodo, nil

}

// stream -> interface generated by gRPC,which has Send() function
func (s *TodoServer) ListTodos(empty *proto.Empty, stream proto.TodoService_ListTodosServer) error {
	log.Printf("Listing all todos")
	for _, todo := range s.todos {
		if err := stream.Send(todo); err != nil {
			return err
		}
	}
	return nil
}

// network layer(tcp port)
// application layer(grpc server)
// business logic(TodoServer)
func server() {
	list, err := net.Listen("tcp", PORT) //opens a network port
	if err != nil {
		log.Fatalf("failed connection : %v", err)
	}
	s := grpc.NewServer()
	proto.RegisterTodoServiceServer(s, &TodoServer{}) //which functions to use when requests come.
	log.Printf("Server is listening at %v", list.Addr())

	//s.Serve(list) ->use tcp listener to accept connections and use gRPC server to handle them
	if err := s.Serve(list); err != nil {
		log.Fatalf("failed to serve %v", err)
	}
}
